services:
  - type: web
    name: edulinguauz-backend
    env: python
    workingDirectory: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && gunicorn edulinguauz.wsgi:application --bind 0.0.0.0:$PORT
    plan: free
    region: frankfurt
